name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  LANG: en_US.UTF-8
  TZ: Asia/Tokyo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: NPM install
        run: |
          npm ci
      - name: Run Linter
        run: |
          npm run lint
